data:
  test_split: 0.05
  data_subset: null
  dataloader_workers: 16
  pred_horizon: ${pred_horizon}
  obs_horizon: ${obs_horizon}
  action_horizon: ${action_horizon}
  augment_image: false
  environment: ${environment}
  furniture: ${furniture}
  demo_source: ${demo_source}
  randomness: ${randomness}
  normalization: min_max # min_max, mean_std
  demo_outcome: ${demo_outcome}
  pad_after: true
