regularization:
  feature_layernorm: false
  feature_noise: false
  feature_dropout: false
  weight_decay: 1e-6

  # Ke et al., “Grasping with Chopsticks.”
  # Right now, we use two different but fixed \sigma of 1 cm and 0.1 rad.
  state_noise: False
  
